name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget libgl-dev xcb libxcb-cursor0 libssl-dev

    - name: Install Qt6
      run: |
        wget https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run -O qt-installer.run
        chmod +x qt-installer.run
        ./qt-installer.run --script install-qt-noninteractive.qs

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck
