name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.0'  # Specify the version of Qt you need
        modules: qtquick,qtquickcontrols2,qtsql,qttest,qtnetwork  # Specify the Qt modules you need
        install-deps: 'true'
        setup-python: 'true'
        set-env: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget libgl-dev xcb libxcb-cursor0 libssl-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0  
            
    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck
