name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget libgl-dev xcb libxcb-cursor0 libssl-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0  
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.0'  # Specify the version of Qt you need
        modules: qtquick,qtquickcontrols2,qtsql,qttest,qtnetwork  # Specify the Qt modules you need
            
    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build
